[package]
name = "testst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = { version = "0.9.3", features = ["multithread-image-decoding"] }
glam = "0.24.2"
